port: 0000
host: ""
domain: ""
token: ""
fileChannel: ""
maxFileSize:
  human: "100mb"
  byte: 104857600
analytics:
  enabled: true
  logToDiscord: true
  channelID: ""  
rateLimit:
  enabled: true
  requests: 10
  perSeconds: 30
  message: "Rate limit exceeded. Please try again later."